[package]
name = "bob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
rand = "0.8.5"
thiserror = "1.0.56"

[[bench]]
name = "bob"
harness = false
